### ISSUE TITLE
Python error when running

### ISSUE THREAD

**Issue by mcteixeira** [Leo3418/btrtb#1]
Hello,

I've installed all the files to the correct paths, but when I run `/usr/local/libexec/btrtb/btrtb-upload` I get the following errors.
Can you please advise on these errors?

`
Traceback (most recent call last):
  File "/usr/local/libexec/btrtb/btrtb-upload", line 12, in <module>
    upload(subvol_config=config)
  File "/usr/lib/python3.9/site-packages/btrtb/upload.py", line 70, in upload
    for path in get_remote_snapshot_list(subvol_config)]
  File "/usr/lib/python3.9/site-packages/btrtb/helpers.py", line 89, in get_remote_snapshot_list
    config_json = get_subvol_config(subvol_config)
  File "/usr/lib/python3.9/site-packages/btrtb/config.py", line 110, in get_subvol_config
    raise ValueError(f"unknown config: {subvol_config}")
ValueError: unknown config: home
`

Thank you!

**Comment by Leo3418** [comment]
Hi mcteixeira! Just a heads-up, this project is not fully complete yet, and I'm not currently working on it at this point. I might come back to this project later, but there isn't a definite plan as of now. I will get back to you when I resume the work on it so I will leave this issue here. Meanwhile, you may try to figure it out yourself if you are skilled, or it might be better to consider using another mature Btrfs snapshot management utilitiy, like [btrbk](https://github.com/digint/btrbk).

**Comment by mcteixeira** [comment]
Hi Leo3418,

Thank you for you quick response. I think I'll try btrbk for now
